import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

const PrivacyPolicy = () => {
    return (
        <div className="min-h-screen bg-white dark:bg-black text-neutral-900 dark:text-neutral-100 selection:bg-orange-500/30">
            <nav className="fixed top-0 z-50 w-full border-b border-black/5 bg-white/80 dark:border-white/5 dark:bg-black/80 backdrop-blur-md">
                <div className="mx-auto flex h-16 max-w-5xl items-center px-6">
                    <Link to="/" className="flex items-center gap-2 group text-sm font-bold uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors">
                        <ArrowLeft className="h-4 w-4 group-hover:-translate-x-1 transition-transform" />
                        Back
                    </Link>
                </div>
            </nav>

            <main className="pt-32 pb-20 px-6 mx-auto max-w-3xl">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="space-y-12"
                >
                    <div className="space-y-4">
                        <h1 className="text-4xl sm:text-6xl font-black tracking-tighter uppercase italic text-orange-500">Privacy Policy</h1>
                        <p className="text-xs font-bold uppercase tracking-[0.3em] text-muted-foreground">Last Updated: March 2026</p>
                    </div>

                    <div className="space-y-8 text-neutral-600 dark:text-neutral-400 leading-relaxed font-medium">
                        <section className="space-y-4">
                            <h2 className="text-xl font-bold tracking-tight text-neutral-900 dark:text-white uppercase">01. Data Synthesis</h2>
                            <p>
                                At Lumis, we prioritize the integrity of your code and intelligence layers. We collect minimal telemetry required to power the neural mapping of your projects. This includes encrypted metadata from linked Git repositories and task management tools.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-bold tracking-tight text-neutral-900 dark:text-white uppercase">02. Infrastructure & Logic</h2>
                            <p>
                                Your source code and project data are processed within isolated inference environments. We do not store full copies of your code unless explicitly required for project indexing, and all sensitive data is encrypted at rest using industry-standard protocols.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-bold tracking-tight text-neutral-900 dark:text-white uppercase">03. Neural Privacy</h2>
                            <p>
                                We do not use your private repository data or project intelligence layers to train global models. Your data remains yours. The AI insights generated by Lumis are specific to your instance and are never shared across the platform's user base.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-bold tracking-tight text-neutral-900 dark:text-white uppercase">04. Authentication Nodes</h2>
                            <p>
                                We utilize Third-Party Auth providers (Supabase/Google) to secure your identity. Lumis never stores your primary account passwords. For external integrations like Jira or Notion, we only store encrypted access tokens required for synchronization protocol.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-bold tracking-tight text-neutral-900 dark:text-white uppercase">05. Intelligence Revocation</h2>
                            <p>
                                At any time, you can revoke access to any repository or integration node. Deleting a project within Lumis will trigger a terminal wipe protocol, removing all cached intelligence associated with that project from our system.
                            </p>
                        </section>
                    </div>

                    <footer className="pt-20 border-t border-black/5 dark:border-white/5">
                        <div className="flex flex-col gap-2">
                            <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Engineering Contact</span>
                            <span className="text-sm font-bold">david@novagate-solutions.com</span>
                        </div>
                    </footer>
                </motion.div>
            </main>
        </div>
    );
};

export default PrivacyPolicy;
